
version: 2.1 

workflows:
  test-env-vars:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: "what is your name?"
          command: |
            echo $MY_ENV_VAR
          environment:
            MY_ENV_VAR: "Shehu Yusuf"